config/routes.rb
Orders::Engine.routes.draw do
  resources :purchase_orders
end

app/models/orders/application_record.rb
module Orders
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/orders/purchase_order.rb
module Orders
  class PurchaseOrder < ApplicationRecord
  end
end

app/controllers/orders/application_controller.rb
module Orders
  class ApplicationController < ActionController::Base
  end
end

app/controllers/orders/purchase_orders_controller.rb
module Orders
  class PurchaseOrdersController < ApplicationController
    before_action :set_purchase_order, only: %i[ show edit update destroy ]

    # GET /purchase_orders
    def index
      @purchase_orders = PurchaseOrder.all
    end

    # GET /purchase_orders/1
    def show
    end

    # GET /purchase_orders/new
    def new
      @purchase_order = PurchaseOrder.new
    end

    # GET /purchase_orders/1/edit
    def edit
    end

    # POST /purchase_orders
    def create
      @purchase_order = PurchaseOrder.new(purchase_order_params)

      if @purchase_order.save
        redirect_to @purchase_order, notice: "Purchase order was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /purchase_orders/1
    def update
      if @purchase_order.update(purchase_order_params)
        redirect_to @purchase_order, notice: "Purchase order was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /purchase_orders/1
    def destroy
      @purchase_order.destroy!
      redirect_to purchase_orders_url, notice: "Purchase order was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_purchase_order
        @purchase_order = PurchaseOrder.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def purchase_order_params
        params.require(:purchase_order).permit(:order_number, :supplier, :order_date, :total_amount, :status)
      end
  end
end

app/helpers/orders/application_helper.rb
module Orders
  module ApplicationHelper
  end
end

app/helpers/orders/purchase_orders_helper.rb
module Orders
  module PurchaseOrdersHelper
  end
end

app/views/layouts/orders/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Orders</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "orders/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/purchase_orders/_form.html.erb
<%= form_with(model: purchase_order) do |form| %>
  <% if purchase_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(purchase_order.errors.count, "error") %> prohibited this purchase_order from being saved:</h2>

      <ul>
        <% purchase_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_number, style: "display: block" %>
    <%= form.text_field :order_number %>
  </div>

  <div>
    <%= form.label :supplier, style: "display: block" %>
    <%= form.text_field :supplier %>
  </div>

  <div>
    <%= form.label :order_date, style: "display: block" %>
    <%= form.date_field :order_date %>
  </div>

  <div>
    <%= form.label :total_amount, style: "display: block" %>
    <%= form.text_field :total_amount %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/purchase_orders/_purchase_order.html.erb
<div id="<%= dom_id purchase_order %>">
  <p>
    <strong>Order number:</strong>
    <%= purchase_order.order_number %>
  </p>

  <p>
    <strong>Supplier:</strong>
    <%= purchase_order.supplier %>
  </p>

  <p>
    <strong>Order date:</strong>
    <%= purchase_order.order_date %>
  </p>

  <p>
    <strong>Total amount:</strong>
    <%= purchase_order.total_amount %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= purchase_order.status %>
  </p>

</div>

app/views/orders/purchase_orders/edit.html.erb
<h1>Editing purchase order</h1>

<%= render "form", purchase_order: @purchase_order %>

<br>

<div>
  <%= link_to "Show this purchase order", @purchase_order %> |
  <%= link_to "Back to purchase orders", purchase_orders_path %>
</div>

app/views/orders/purchase_orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Purchase orders</h1>

<div id="purchase_orders">
  <% @purchase_orders.each do |purchase_order| %>
    <%= render purchase_order %>
    <p>
      <%= link_to "Show this purchase order", purchase_order %>
    </p>
  <% end %>
</div>

<%= link_to "New purchase order", new_purchase_order_path %>

app/views/orders/purchase_orders/new.html.erb
<h1>New purchase order</h1>

<%= render "form", purchase_order: @purchase_order %>

<br>

<div>
  <%= link_to "Back to purchase orders", purchase_orders_path %>
</div>

app/views/orders/purchase_orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @purchase_order %>

<div>
  <%= link_to "Edit this purchase order", edit_purchase_order_path(@purchase_order) %> |
  <%= link_to "Back to purchase orders", purchase_orders_path %>

  <%= button_to "Destroy this purchase order", @purchase_order, method: :delete %>
</div>